### ISSUE TITLE
colcon build error for [point_cloud_perception] packages

### ISSUE THREAD

**Issue by KimDoYoung1997** [noshluk2/ros2_learners#4]
hello luqman. I'm watching your video well. Thank you a lot.

https://www.youtube.com/watch?v=VCobOzw2kHM

when I followed your video, i got some build issues. can you help me?

**systme environment ** : 
 OS :Ubuntu 20.04 
 ROS: FOXY 
 workspace : ros2_ws

and I command below

$ sudo apt install libpcl-dev
$ sudo apt-get install ros-foxy-pcl-ros
$ sudo apt-get install ros-foxy-pcl-conversion
$ cd ~/ros2_ws/src
$ git clone https://github.com/noshluk2/ros2_learners.git
$ cd ~/ros2_ws
$ rosdep install --from-paths src --ignore-src -r -y
$ colcon build --symlink-install

when I colcon build, I got this error.
![image](https://user-images.githubusercontent.com/97829134/217127113-51d78f9e-46f2-40be-b7d2-54459ca81c9b.png)
Starting >>> navigation_
Starting >>> nodes
Starting >>> point_cloud_perception
--- stderr: point_cloud_perception                                                   
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:62 (message):
  common is required but boost was not found
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:367 (pcl_report_not_found)
  /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:551 (find_external_library)
  CMakeLists.txt:10 (find_package)

---
Failed   <<< point_cloud_perception [0.17s, exited with code 1]
Aborted  <<< navigation_ [0.38s]                                           
Aborted  <<< nodes [0.38s]

Summary: 0 packages finished [0.48s]
  1 package failed: point_cloud_perception
  2 packages aborted: navigation_ nodes
  1 package had stderr output: point_cloud_perception

I think pcl library is not compatible with my system..

how can i fix it?

thank you sincerely for your lecture.

**Comment by noshluk2** [comment]
Kindly run this command as well 

```
sudo apt-get install pcl-tools
```

**Comment by KimDoYoung1997** [comment]
Thank you for kind reply lugman!

actually I already remove that package and resintall pcl-tools.

but error is below..



Im sorry to bother you.

Thank you.

-----Original Message-----

**Comment by JPJSea** [comment]
Your issue is related to cmake not being able to find Boost and nothing to do with reinstalling pcl-tools

The following information in your screenshot is relevent:
> common is required but boost was not found

If you have boost installed on your system, CMake is probably looking for it in the wrong place. This may help you:
https://github.com/PointCloudLibrary/pcl/issues/5052#issuecomment-984042504

**Comment by noshluk2** [comment]
@KimDoYoung1997 is it now solved after installing boost library?

**Comment by KimDoYoung1997** [comment]
@noshluk2  nope.. still have problem. is it the problem that my ROS version is foxy?

**Comment by KimDoYoung1997** [comment]
@noshluk2 
hi Im sorry to be late.. actually not yet. so I decided to use new computer and then it is solved..
