### ISSUE TITLE
Nav 2 : Robot Nav2 Setup for Mobile Robots

### ISSUE THREAD

**Issue by noshluk2** [noshluk2/ros2_learners#6]
## Autnomous Navigation

- Use turtlebot3 for Mapping
- Setup Navigation Pipelines
- Rviz2 to send Multi Goal

**Comment by ER-ROUGUI** [comment]
Hello I hope you're doing well , Thank you the explanation 
for the issue **Nav 2 : Robot Nav2 Setup for mobile Robots**  
I tried to launch the mapping launch file but  i get an Error   **the package has successfully build**
######################

[ERROR] [cartographer_node-1]: process[cartographer_node-1] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [cartographer_node-1]: sending signal 'SIGTERM' to process[cartographer_node-1]


process has died [pid 178530, exit code -15, cmd '/opt/ros/foxy/lib/cartographer_ros/cartographer_node -configuration_directory /home/robot_ws/install/navigation_/share/navigation_/config -configuration_basename turtlebot3_lds_2d.lua --ros-args -r __node:=mapping_node'].

#####################

I use Ros2 foxy and ubuntu 20

Thank you
